### PR TITLE
Allow for Python 3.9 support

### PR DESCRIPTION
**Pull request by bpkroth**
# Pull Request

## Title

Allow for Python 3.9 support

---

## Description

- Relaxes packaging requirements to allow for Python 3.9 support.
- Adds Python 3.9 to the CI pipeline matrix.
- ~Adds basic instructions for using `conda` to the CONTRIBUTING documentation (moved to #83).~

- #78 

---

## Type of Change

- 🛠️ Bug fix  
- 📝 Documentation update  

---

## Additional Notes

Initially we attempted to allow Python 3.8 as well, but it had some logging bugs that we didn't track down.

Details in the PR notes on Github.

---

### CODE REVIEW

**Comment by bpkroth** [comment]
Currently failing on logging error with 3.8.

Could use some help fixing that:

```python
    def test_exception_in_to_json(self):
        config = ClusterStateConfig(config_dict=self.config_data)

        # Simulate an error when trying to write to a file
        with patch('builtins.open', mock_open()) as mocked_file:
            mocked_file.side_effect = Exception("File write error")

            # Capture logs at the ERROR level
            with self.assertLogs('root', level='ERROR') as log:
                try:
                    config.to_json("dummy.json")
                except Exception:
>                   pass  # Exception is expected, so we suppress it here
E                   AssertionError: no logs of level ERROR or higher triggered on root

tests/test_cluster_state_config.py:127: AssertionError
----------------------------------------------------------------------------------------------------- Captured log call ------------------------------------------------------------------------------------------------------
ERROR    root:ClusterStateConfig.py:75 Error writing JSON file: File write error
================================================================================================== short test summary info ===================================================================================================
FAILED tests/test_cluster_state_config.py::TestClusterStateConfig::test_exception_in_to_json - AssertionError: no logs of level ERROR or higher triggered on root
```

**Comment by ksaur** [comment]
Sorry for the wild goose chase, maybe just keep your edits to `contributing.md`, discard the rest, and then we close #78 and leave it there in case others hit same issues? What do you think?

**Comment by bpkroth** [comment]
I'll split it out and make a new PR for the docs and we can close this one. Will make it easier to resurrect in the future if we care to.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Review by ksaur — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
