### PR TITLE
Test runner improvements

### LINKED ISSUE #60: Parallelize tests
Investigate using `pytest-xdist` to parallelize tests.

### PR DESCRIPTION
**Pull request by bpkroth**
# Pull Request

## Title

Various test runner improvements.

---

## Description

- Creates a temporary working directory per test runner.
- Uses xdist to parallelize tests.
- Produce coverage report directly from pytest.
- Require minimum coverage level.
- Adjust documentation.
- Add vscode config files for more ergonomic debugging of tests.

- Closes #60

---

## Type of Change

- ✨ New feature  
- 📝 Documentation update  
- 🧪 Tests

---

### CODE REVIEW

**Comment by jcamachor** [comment]
There appears to be an issue with generating the coverage report.

**Comment by bpkroth** [comment]
Probably invoking coverage via pytest rather than the other way around will solve that. I'll make the change tomorrow.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by bpkroth** [comment]
@jcamachor we should probably also require a minimal coverage so this gets caught in the future automatically

**Review by ksaur — APPROVED** [review]
LGTM!

**Pull request merged**
